name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 18 * * 2"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: malith-rukshan
          template: classic
          base: header, metadata
          config_timezone: Asia/Colombo
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_details: percentage, lines
          plugin_languages_sections: most-used, recently-used
          plugin_languages_ignored: HTML, CSS, Less, EJS, TSX
          plugin_languages_other: true
          plugin_people: no
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers
